name: "CliqInformer"
description: "The Github Action is used to Integrate Github and Zoho Cliq by Notifying about the Github Events Performed to the Zoho Cliq Channels."

branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  cliq-webhook:
    description: "Webhook to Integrate with your Zoho Account in Cliq"
    required: true
  channel-endpoint:
    description: "Endpoint of the Channel you would like to Integrate with in Cliq"
    required: true
  message:
    description: "The Message to be Delivered to the Cliq Channel"

outputs:
  message-status:
    description: "The Status of Reception of the Message in the Zoho Cliq Application"
    value: 200

runs:
  using: "composite"
  steps:
      - name: Set Up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Set Up Checkout
        uses: actions/checkout@v3
      - name: "Running the Cliq Integration"
        shell: bash
        run: |
          JAVA=$JAVA_HOME_19_X64/bin/java
          CONNECTOR=$GITHUB_ACTION_PATH/src/CliqInformer.java
            $JAVA $CONNECTOR ${{inputs.cliq-webhook}} ${{inputs.channel-endpoint}} "$GITHUB_EVENT_NAME" "$GITHUB_SERVER_URL" "$GITHUB_REPOSITORY" "$GITHUB_WORKFLOW" "$GITHUB_ACTOR" "$GITHUB_RUN_ID" "${{inputs.message}}"
